-- Import 2025 biology exam questions with images and answer analysis.
USE smart_learning;
START TRANSACTION;
CREATE TEMPORARY TABLE tmp_biology_import_questions AS
SELECT id FROM question WHERE source = '2025高考课标卷生物';
CREATE TEMPORARY TABLE tmp_biology_import_exams AS
SELECT id FROM exam_paper WHERE name = '2025高考课标卷生物真题训练';
DELETE pa FROM practice_answer pa JOIN tmp_biology_import_questions q ON q.id = pa.question_id;
DELETE ar FROM answer_record ar JOIN tmp_biology_import_questions q ON q.id = ar.question_id;
DELETE mb FROM mistake_book mb JOIN tmp_biology_import_questions q ON q.id = mb.question_id;
DELETE eq FROM exam_question eq JOIN tmp_biology_import_questions q ON q.id = eq.question_id;
DELETE eq FROM exam_question eq JOIN tmp_biology_import_exams e ON e.id = eq.exam_id;
DELETE es FROM exam_submission es JOIN tmp_biology_import_exams e ON e.id = es.exam_id;
DELETE FROM exam_paper WHERE id IN (SELECT id FROM tmp_biology_import_exams);
DELETE FROM question WHERE id IN (SELECT id FROM tmp_biology_import_questions);
INSERT INTO subject (name, description, icon, sort_order) SELECT '生物', '生物科目', 'dna', 6 WHERE NOT EXISTS (SELECT 1 FROM subject WHERE name = '生物');
SET @admin_id := (SELECT id FROM user WHERE role = 'ADMIN' ORDER BY id LIMIT 1);
SET @subject_biology := (SELECT id FROM subject WHERE name = '生物' ORDER BY id LIMIT 1);
INSERT INTO knowledge_point (subject_id, name, parent_id, level, description) SELECT @subject_biology, '生命的物质基础', 0, 1, '蛋白质、核酸等生命大分子的结构与功能' WHERE NOT EXISTS (SELECT 1 FROM knowledge_point WHERE subject_id = @subject_biology AND name = '生命的物质基础');
SET @kp_80f50ccada := (SELECT id FROM knowledge_point WHERE subject_id = @subject_biology AND name = '生命的物质基础' ORDER BY id LIMIT 1);
INSERT INTO knowledge_point (subject_id, name, parent_id, level, description) SELECT @subject_biology, '细胞代谢', 0, 1, '光合作用、呼吸作用和物质能量变化' WHERE NOT EXISTS (SELECT 1 FROM knowledge_point WHERE subject_id = @subject_biology AND name = '细胞代谢');
SET @kp_b90100844e := (SELECT id FROM knowledge_point WHERE subject_id = @subject_biology AND name = '细胞代谢' ORDER BY id LIMIT 1);
INSERT INTO knowledge_point (subject_id, name, parent_id, level, description) SELECT @subject_biology, '生命活动调节', 0, 1, '神经调节、体液调节和激素调节' WHERE NOT EXISTS (SELECT 1 FROM knowledge_point WHERE subject_id = @subject_biology AND name = '生命活动调节');
SET @kp_d3501f6e77 := (SELECT id FROM knowledge_point WHERE subject_id = @subject_biology AND name = '生命活动调节' ORDER BY id LIMIT 1);
INSERT INTO knowledge_point (subject_id, name, parent_id, level, description) SELECT @subject_biology, '遗传与育种', 0, 1, '遗传规律、变异、育种和性状分析' WHERE NOT EXISTS (SELECT 1 FROM knowledge_point WHERE subject_id = @subject_biology AND name = '遗传与育种');
SET @kp_324f0869ea := (SELECT id FROM knowledge_point WHERE subject_id = @subject_biology AND name = '遗传与育种' ORDER BY id LIMIT 1);
INSERT INTO knowledge_point (subject_id, name, parent_id, level, description) SELECT @subject_biology, '生态系统', 0, 1, '种群、群落、生态系统结构与稳定性' WHERE NOT EXISTS (SELECT 1 FROM knowledge_point WHERE subject_id = @subject_biology AND name = '生态系统');
SET @kp_a0f0ef1108 := (SELECT id FROM knowledge_point WHERE subject_id = @subject_biology AND name = '生态系统' ORDER BY id LIMIT 1);
INSERT INTO knowledge_point (subject_id, name, parent_id, level, description) SELECT @subject_biology, '免疫调节', 0, 1, '免疫系统、免疫失调和免疫应答' WHERE NOT EXISTS (SELECT 1 FROM knowledge_point WHERE subject_id = @subject_biology AND name = '免疫调节');
SET @kp_8ee639aa38 := (SELECT id FROM knowledge_point WHERE subject_id = @subject_biology AND name = '免疫调节' ORDER BY id LIMIT 1);
INSERT INTO knowledge_point (subject_id, name, parent_id, level, description) SELECT @subject_biology, '生物技术与实验', 0, 1, 'PCR、电泳、基因工程和实验设计' WHERE NOT EXISTS (SELECT 1 FROM knowledge_point WHERE subject_id = @subject_biology AND name = '生物技术与实验');
SET @kp_19e71442ab := (SELECT id FROM knowledge_point WHERE subject_id = @subject_biology AND name = '生物技术与实验' ORDER BY id LIMIT 1);
INSERT INTO knowledge_point (subject_id, name, parent_id, level, description) SELECT @subject_biology, '细胞结构与物质运输', 0, 1, '细胞结构、渗透作用和跨膜运输' WHERE NOT EXISTS (SELECT 1 FROM knowledge_point WHERE subject_id = @subject_biology AND name = '细胞结构与物质运输');
SET @kp_dbab295fc6 := (SELECT id FROM knowledge_point WHERE subject_id = @subject_biology AND name = '细胞结构与物质运输' ORDER BY id LIMIT 1);
INSERT INTO exam_paper (name, subject_id, creator_id, total_score, duration, description, status, created_at) VALUES ('2025高考课标卷生物真题训练', @subject_biology, @admin_id, 100, 90, '2025高考课标卷生物导入真题，含题图、答案和解析', 1, NOW());
SET @exam_id := LAST_INSERT_ID();
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_biology, CAST(@kp_80f50ccada AS CHAR), 'SINGLE_CHOICE', '【2025高考课标卷生物·第1题】<br>1. 蛋白质是结构和功能多样的生物大分子。下列叙述错误的是（）', '["二硫键的断裂不会改变蛋白质的空间结构", "改变蛋白质的空间结构可能会影响其功能", "用乙醇等有机溶剂处理可使蛋白质发生变性", "利用蛋白质工程可获得氨基酸序列改变的蛋白质"]', 'A', '参考答案：A', 3, '2025高考课标卷生物', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 6, 1);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_biology, CAST(@kp_b90100844e AS CHAR), 'SINGLE_CHOICE', '【2025高考课标卷生物·第2题】<br>2. 在一定温度下，生长在大田的某种植物光合速率（CO2固定速率）和呼吸速率（CO2释放速率）对光照强度的响应曲线如图所示。下列叙述错误的是（）<div class="question-images"><img src="/images/questions/2025/biology/img_001.png" alt="题目配图"></div>', '["光照强度为a时，该植物的干重不会增加", "光照强度从a逐渐增加到b时，该植物生长速率逐渐增大", "光照强度小于b时，提高大田CO2浓度，CO2固定速率会增大", "光照强度为b时，适当降低光反应速率，CO2固定速率会降低"]', 'C', '参考答案：C', 3, '2025高考课标卷生物', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 6, 2);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_biology, CAST(@kp_d3501f6e77 AS CHAR), 'SINGLE_CHOICE', '【2025高考课标卷生物·第3题】<br>3. 为研究肾上腺的生理机能，某研究小组将小鼠按照下表进行处理，一定时间后检测相关指标。<br>分组<br>实验处理<br>甲<br>不摘除肾上腺<br>乙<br>摘除肾上腺<br>丙<br>摘除肾上腺，注射醛固酮<br>下列叙述错误的是（）', '["乙组小鼠的促肾上腺皮质激素水平会升高", "乙组小鼠饮生理盐水有利于改善水盐平衡", "三组小鼠均饮清水时，丙组小鼠血钠含量最低", "甲组小鼠受寒冷刺激时，肾上腺素释放量增加"]', 'C', '参考答案：C', 3, '2025高考课标卷生物', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 6, 3);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_biology, CAST(@kp_a0f0ef1108 AS CHAR), 'SINGLE_CHOICE', '【2025高考课标卷生物·第4题】<br>4. 某同学在甲、乙两个植物群落中设置样方调查其特征，样方中植物的物种数随样方面积扩大而逐渐增加，但样方面积扩大到一定程度后物种数的变化明显趋缓（如图所示），此时对应的样方面积（a和b）通常称为最小面积。下列叙述错误的是（）<div class="question-images"><img src="/images/questions/2025/biology/img_002.png" alt="题目配图"></div>', '["最小面积样方中应包含群落中绝大多数的物种", "与甲相比，乙群落的物种丰富度较高，调查时最小面积更大", "调查甲群落的物种丰富度时，设置的样方面积应不小于a", "调查乙群落中植物的种群密度时，针对每种植物设置的样方面积应不小于b"]', 'D', '参考答案：D', 3, '2025高考课标卷生物', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 6, 4);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_biology, CAST(@kp_324f0869ea AS CHAR), 'SINGLE_CHOICE', '【2025高考课标卷生物·第5题】<br>5. 为获得作物新品种，可采用不同的育种技术。下列叙述错误的是（）', '["三倍体西瓜育种时，利用了人工诱导染色体加倍获得的多倍体", "作物单倍体育种时，利用了由植物茎尖组织培养获得的单倍体", "航天育种时，利用了太空多种因素导致基因突变产生的突变体", "水稻杂交育种时，利用了水稻有性繁殖过程中产生的重组个体"]', 'B', '参考答案：B', 3, '2025高考课标卷生物', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 6, 5);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_biology, CAST(@kp_19e71442ab AS CHAR), 'SINGLE_CHOICE', '【2025高考课标卷生物·第6题】<br>6. 琼脂糖凝胶电泳常用于核酸样品的分析，样品1～4的电泳结果如图所示（“+”“-”分别代表电泳槽的阳极和阴极）。已知样品1和2中的DNA分子分别是甲和乙，甲只有限制酶R的一个酶切位点，样品3和4中有一个样品是甲的酶切产物。下列叙述错误的是（）<div class="question-images"><img src="/images/questions/2025/biology/img_003.png" alt="题目配图"></div>', '["配制琼脂糖凝胶时需选用适当 缓冲溶液", "该实验条件下甲、乙两种DNA分子均带负电荷", "甲、乙两种DNA分子所含碱基对的数量可能不同", "据图推测样品3可能是甲被酶R完全酶切后的产物"]', 'D', '参考答案：D', 3, '2025高考课标卷生物', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 6, 6);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_biology, CAST(@kp_dbab295fc6 AS CHAR), 'ESSAY', '【2025高考课标卷生物·第7题】<br>7. 将某植物叶肉细胞放入一定浓度 KCl溶液中，起初细胞失水发生质壁分离，一定时间（t）后细胞开始吸水，并逐渐复原。回答下列问题：<br>（1）植物细胞与外界溶液进行水分交换时，水分子跨膜运输的两种方式是________。<br>（2）细胞失水发生质壁分离，原生质层与细胞壁分离的原因是________。<br>（3）一定时间（t）后细胞开始吸水的原因是________。', NULL, '（1）自由扩散、协助扩散<br>（2）细胞失水体积缩小，原生质层比细胞壁的伸缩性大<br>（3）K+和C1-进入细胞，使细胞内渗透压高于外界溶液', '参考答案：<br>（1）自由扩散、协助扩散<br>（2）细胞失水体积缩小，原生质层比细胞壁的伸缩性大<br>（3）K+和C1-进入细胞，使细胞内渗透压高于外界溶液', 3, '2025高考课标卷生物', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 15, 7);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_biology, CAST(@kp_8ee639aa38 AS CHAR), 'ESSAY', '【2025高考课标卷生物·第8题】<br>8. 有研究显示，机体内蛋白P表达量降低会引起免疫失调。已知酶E可催化蛋白P基因的启动子甲基化，酶E被磷酸化后失活。研究人员用酶E（或磷酸化的酶E）、含蛋白P基因及其启动子的表达质粒等进行实验，结果如图所示。回答下列问题：<br>（1）免疫失调包括过敏反应和________（答出2点即可）等。<br>（2）根据实验结果判断，蛋白P基因的启动子甲基化________（填“促进”“抑制”或“不影响”）蛋白P的表达，判断依据是________。<br>（3）为治疗因蛋白P表达量降低起的免疫失调，可使用抑制________（填“酶E”“磷酸化的酶E”或“蛋白P”）活性的药物。免疫失调也可以通过调节抗体的生成进行治疗，机体产生抗体过程中记忆B细胞的作用是________。<div class="question-images"><img src="/images/questions/2025/biology/img_004.png" alt="题目配图"></div>', NULL, '（1）自身免疫病、免疫缺陷病<br>（2） ①. 抑制 ②. 酶E催化蛋白P基因的启动子甲基化，酶E含量增加导致蛋白P的表达量下降，磷酸化的酶E含量增加不会影响蛋白P的表达量<br>（3） ①. 酶E ②. 再次接触抗原时，能迅速增殖分化，快速产生大量抗体', '参考答案：<br>（1）自身免疫病、免疫缺陷病<br>（2） ①. 抑制 ②. 酶E催化蛋白P基因的启动子甲基化，酶E含量增加导致蛋白P的表达量下降，磷酸化的酶E含量增加不会影响蛋白P的表达量<br>（3） ①. 酶E ②. 再次接触抗原时，能迅速增殖分化，快速产生大量抗体', 3, '2025高考课标卷生物', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 15, 8);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_biology, CAST(@kp_a0f0ef1108 AS CHAR), 'ESSAY', '【2025高考课标卷生物·第9题】<br>9. 在“绿水青山就是金山银山”理念的感召下，同学们积极讨论某退化荒山的生态恢复方案。A同学提出选择一种树种进行全覆盖造林；B同学提出应该种植多种草本和木本植物。回答下列问题：<br>（1）在生态恢复过程中，退化荒山会发生群落演替。通常，群落演替的类型有初生演替和次生演替，二者的区别有________（答出2点即可）。<br>（2）与A同学的方案相比，B同学的方案可能有利于控制害虫的爆发，从种间关系的角度分析其原因是________。<br>（3）为合理利用环境资源，从群落空间结构的角度考虑，设计荒山绿化方案时应遵循的原则是________（答出2点即可）。<br>（4）为维护恢复后生态系统的稳定性，需要采取的措施有________（答出2点即可）。', NULL, '（1）起点不同；速度不同<br>（2）B同学方案中植物种类多，动物种类会相应增加，物种间的竞争、捕食等关系更复杂，使害虫种群数量增长受到限制<br>（3）群落水平方向上种植不同种类 植物；群落垂直方向上种植不同高度的植物<br>（4）控制对生态系统的干扰强度；给予相应的物质、能量投入', '参考答案：<br>（1）起点不同；速度不同<br>（2）B同学方案中植物种类多，动物种类会相应增加，物种间的竞争、捕食等关系更复杂，使害虫种群数量增长受到限制<br>（3）群落水平方向上种植不同种类 植物；群落垂直方向上种植不同高度的植物<br>（4）控制对生态系统的干扰强度；给予相应的物质、能量投入', 3, '2025高考课标卷生物', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 15, 9);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_biology, CAST(@kp_324f0869ea AS CHAR), 'ESSAY', '【2025高考课标卷生物·第10题】<br>10. 植物合成的色素会影响花色。某二倍体植物的花色有深红、浅红和白三种表型。研究小组用甲、乙两个浅红色表型的植株进行相关实验。回答下列问题：<br>（1）甲、乙分别自交，子一代均出现浅红色：白色=3：1的表型分离比；甲和乙杂交，子一代出现深红色（丙）：浅红色：白色（丁）=1：2：1的表型分离比。综上判断，甲和乙的基因型________（填“相同”或“不同”），判断依据是________。<br>（2）丙自交子一代出现深红色：浅红色：白色=9：6：1的表型分离比，其中与丙基因型相同的个体所占比例为________。若丙与丁杂交，子一代的表型及分离比为________，其中纯合体所占比例为________。', NULL, '（1） ①. 不同 ②. 甲、乙自交的结果与甲乙杂交的结果不同<br>（2） ①. 1/4 ②. 深红色:浅红色:白色=1:2:1 ③. 1/4', '参考答案：<br>（1） ①. 不同 ②. 甲、乙自交的结果与甲乙杂交的结果不同<br>（2） ①. 1/4 ②. 深红色:浅红色:白色=1:2:1 ③. 1/4', 4, '2025高考课标卷生物', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 15, 10);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_biology, CAST(@kp_19e71442ab AS CHAR), 'ESSAY', '【2025高考课标卷生物·第11题】<br>11. 为在大肠杆菌中表达酶X，某同学将编码酶X的基因（目的基因）插入质粒P0，构建重组质粒Px，并转入大肠杆菌。该同学设计引物用PCR方法验证重组质粒构建成功（引物1~4结合位置如图所示，→表示引物5＇→3＇方向）。回答下列问题：<br>（1）PCR是根据DNA复制原理在体外扩增DNA的技术。在细胞中DNA复制时解开双链的酶是________，而PCR过程中解开双链的方法是________。<br>（2）PCR过程中，因参与合成反应、不断消耗而浓度下降的组分有________。<br>（3）该同学进行PCR实验时，所用模板与引物见下表。实验中①和④的作用是：________；②无扩增产物，原因是________；③、⑤和⑥有扩增产物，扩增出的DNA产物分别是________。<br>管号<br>①<br>②<br>③<br>④<br>⑤<br>⑥<br>模板<br>无<br>P0<br>Px<br>无<br>P0<br>Px<br>引物对<br>引物1和引物2<br>引物3和引物4<br>（4）设计实验验证大肠杆菌表达 酶X有活性，简要写出实验思路和预期结果________。<div class="question-images"><img src="/images/questions/2025/biology/img_005.png" alt="题目配图"></div>', NULL, '（1） ①. 解旋酶 ②. 高温变性<br>（2）引物、脱氧核苷三磷酸<br>（3） ①. 作为对照（或答:鉴定反应体系是否有模板污染） ②. P0不含与引物1和引物2互补的碱基序列 ③. 目的基因、质粒片段、含目的基因和部分质粒序列的片段<br>（4）提取酶X，催化相应底物（反应物）的反应，检测是否有产物生成。有产物生成，则证明酶X有活性', '参考答案：<br>（1） ①. 解旋酶 ②. 高温变性<br>（2）引物、脱氧核苷三磷酸<br>（3） ①. 作为对照（或答:鉴定反应体系是否有模板污染） ②. P0不含与引物1和引物2互补的碱基序列 ③. 目的基因、质粒片段、含目的基因和部分质粒序列的片段<br>（4）提取酶X，催化相应底物（反应物）的反应，检测是否有产物生成。有产物生成，则证明酶X有活性', 4, '2025高考课标卷生物', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 15, 11);
DROP TEMPORARY TABLE tmp_biology_import_questions;
DROP TEMPORARY TABLE tmp_biology_import_exams;
COMMIT;
