-- Import 2025 physics exam questions with images and answer analysis.
USE smart_learning;
START TRANSACTION;
CREATE TEMPORARY TABLE tmp_physics_import_questions AS
SELECT id FROM question WHERE source = '2025高考课标卷物理';
CREATE TEMPORARY TABLE tmp_physics_import_exams AS
SELECT id FROM exam_paper WHERE name = '2025高考课标卷物理真题训练';
DELETE pa FROM practice_answer pa JOIN tmp_physics_import_questions q ON q.id = pa.question_id;
DELETE ar FROM answer_record ar JOIN tmp_physics_import_questions q ON q.id = ar.question_id;
DELETE mb FROM mistake_book mb JOIN tmp_physics_import_questions q ON q.id = mb.question_id;
DELETE eq FROM exam_question eq JOIN tmp_physics_import_questions q ON q.id = eq.question_id;
DELETE eq FROM exam_question eq JOIN tmp_physics_import_exams e ON e.id = eq.exam_id;
DELETE es FROM exam_submission es JOIN tmp_physics_import_exams e ON e.id = es.exam_id;
DELETE FROM exam_paper WHERE id IN (SELECT id FROM tmp_physics_import_exams);
DELETE FROM question WHERE id IN (SELECT id FROM tmp_physics_import_questions);
INSERT INTO subject (name, description, icon, sort_order) SELECT '物理', '物理科目', 'atom', 4 WHERE NOT EXISTS (SELECT 1 FROM subject WHERE name = '物理');
SET @admin_id := COALESCE((SELECT id FROM user WHERE role = 'ADMIN' ORDER BY id LIMIT 1), (SELECT MIN(id) FROM user));
SET @subject_physics := (SELECT id FROM subject WHERE name = '物理' ORDER BY id LIMIT 1);
INSERT INTO knowledge_point (subject_id, name, parent_id, level, description) SELECT @subject_physics, '运动学与动力学', 0, 1, '直线运动、牛顿运动定律和受力分析' WHERE NOT EXISTS (SELECT 1 FROM knowledge_point WHERE subject_id = @subject_physics AND name = '运动学与动力学');
SET @kp_e282c42f81 := (SELECT id FROM knowledge_point WHERE subject_id = @subject_physics AND name = '运动学与动力学' ORDER BY id LIMIT 1);
INSERT INTO knowledge_point (subject_id, name, parent_id, level, description) SELECT @subject_physics, '万有引力与航天', 0, 1, '天体运动、卫星轨道和引力规律' WHERE NOT EXISTS (SELECT 1 FROM knowledge_point WHERE subject_id = @subject_physics AND name = '万有引力与航天');
SET @kp_86d0ca46c6 := (SELECT id FROM knowledge_point WHERE subject_id = @subject_physics AND name = '万有引力与航天' ORDER BY id LIMIT 1);
INSERT INTO knowledge_point (subject_id, name, parent_id, level, description) SELECT @subject_physics, '功和能', 0, 1, '动能定理、机械能守恒和能量转化' WHERE NOT EXISTS (SELECT 1 FROM knowledge_point WHERE subject_id = @subject_physics AND name = '功和能');
SET @kp_531fc8d667 := (SELECT id FROM knowledge_point WHERE subject_id = @subject_physics AND name = '功和能' ORDER BY id LIMIT 1);
INSERT INTO knowledge_point (subject_id, name, parent_id, level, description) SELECT @subject_physics, '电场', 0, 1, '电势、电场强度和带电粒子运动' WHERE NOT EXISTS (SELECT 1 FROM knowledge_point WHERE subject_id = @subject_physics AND name = '电场');
SET @kp_329b905917 := (SELECT id FROM knowledge_point WHERE subject_id = @subject_physics AND name = '电场' ORDER BY id LIMIT 1);
INSERT INTO knowledge_point (subject_id, name, parent_id, level, description) SELECT @subject_physics, '磁场', 0, 1, '洛伦兹力、带电粒子在磁场中的运动' WHERE NOT EXISTS (SELECT 1 FROM knowledge_point WHERE subject_id = @subject_physics AND name = '磁场');
SET @kp_97642cdb76 := (SELECT id FROM knowledge_point WHERE subject_id = @subject_physics AND name = '磁场' ORDER BY id LIMIT 1);
INSERT INTO knowledge_point (subject_id, name, parent_id, level, description) SELECT @subject_physics, '热学', 0, 1, '理想气体、状态参量和热力学图像' WHERE NOT EXISTS (SELECT 1 FROM knowledge_point WHERE subject_id = @subject_physics AND name = '热学');
SET @kp_7e26cc7f7a := (SELECT id FROM knowledge_point WHERE subject_id = @subject_physics AND name = '热学' ORDER BY id LIMIT 1);
INSERT INTO knowledge_point (subject_id, name, parent_id, level, description) SELECT @subject_physics, '波动与振动', 0, 1, '机械波、振动和图像分析' WHERE NOT EXISTS (SELECT 1 FROM knowledge_point WHERE subject_id = @subject_physics AND name = '波动与振动');
SET @kp_8ef7997009 := (SELECT id FROM knowledge_point WHERE subject_id = @subject_physics AND name = '波动与振动' ORDER BY id LIMIT 1);
INSERT INTO knowledge_point (subject_id, name, parent_id, level, description) SELECT @subject_physics, '电学实验', 0, 1, '电路测量、传感器和实验数据处理' WHERE NOT EXISTS (SELECT 1 FROM knowledge_point WHERE subject_id = @subject_physics AND name = '电学实验');
SET @kp_da1baf7adf := (SELECT id FROM knowledge_point WHERE subject_id = @subject_physics AND name = '电学实验' ORDER BY id LIMIT 1);
INSERT INTO knowledge_point (subject_id, name, parent_id, level, description) SELECT @subject_physics, '电容器', 0, 1, '电容器、电介质和电场能量' WHERE NOT EXISTS (SELECT 1 FROM knowledge_point WHERE subject_id = @subject_physics AND name = '电容器');
SET @kp_c35cb6d924 := (SELECT id FROM knowledge_point WHERE subject_id = @subject_physics AND name = '电容器' ORDER BY id LIMIT 1);
INSERT INTO knowledge_point (subject_id, name, parent_id, level, description) SELECT @subject_physics, '动量与机械能', 0, 1, '碰撞、弹簧模型和综合力学' WHERE NOT EXISTS (SELECT 1 FROM knowledge_point WHERE subject_id = @subject_physics AND name = '动量与机械能');
SET @kp_15ccef12ae := (SELECT id FROM knowledge_point WHERE subject_id = @subject_physics AND name = '动量与机械能' ORDER BY id LIMIT 1);
INSERT INTO exam_paper (name, subject_id, creator_id, total_score, duration, description, status, created_at) VALUES ('2025高考课标卷物理真题训练', @subject_physics, @admin_id, 100, 90, '2025高考课标卷物理导入真题，含题图、答案和解析', 1, NOW());
SET @exam_id := LAST_INSERT_ID();
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_physics, CAST(@kp_e282c42f81 AS CHAR), 'SINGLE_CHOICE', '【2025高考课标卷物理·第1题】<br>1. 我国自主研发的CR450动车组试验时的速度可达450km/h。若以120m/s的初速度在平直轨道上行驶的CR450动车组，匀减速运行14.4km后停止，则减速运动中其加速度的大小为（　　）', '["0.1m/s2", "0.5m/s2", "1.0m/s2", "1.5m/s2"]', 'B', '参考答案：B', 3, '2025高考课标卷物理', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 6, 1);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_physics, CAST(@kp_86d0ca46c6 AS CHAR), 'SINGLE_CHOICE', '【2025高考课标卷物理·第2题】<br>2. “天都一号”通导技术试验卫星测距试验的成功，标志着我国在深空轨道精密测量领域取得了技术新突破。“天都一号”在环月椭圆轨道上运行时，（　　）', '["受月球的引力大小保持不变", "相对月球的速度大小保持不变", "离月球越近，其相对月球 速度越大", "离月球越近，其所受月球的引力越小"]', 'C', '参考答案：C', 3, '2025高考课标卷物理', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 6, 2);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_physics, CAST(@kp_531fc8d667 AS CHAR), 'SINGLE_CHOICE', '【2025高考课标卷物理·第3题】<br>3. 如图，撑杆跳高运动中，运动员经过助跑、撑杆起跳，最终越过横杆。若运动员起跳前助跑速度为10m/s，则理论上运动员助跑获得 动能可使其重心提升的最大高度为（重力加速度取10m/s2）（　　）<div class="question-images"><img src="/images/questions/2025/physics/img_001.png" alt="题目配图"></div>', '["4m", "5m", "6m", "7m"]', 'B', '参考答案：B', 3, '2025高考课标卷物理', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 6, 3);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_physics, CAST(@kp_329b905917 AS CHAR), 'SINGLE_CHOICE', '【2025高考课标卷物理·第4题】<br>4. 匀强电场中，一带正电的点电荷仅在电场力的作用下以某一初速度开始运动，则运动过程中，其（　　）', '["所处位置的电势一定不断降低", "所处位置的电势一定不断升高", "轨迹可能是与电场线平行 直线", "轨迹可能是与电场线垂直的直线"]', 'C', '参考答案：C', 3, '2025高考课标卷物理', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 6, 4);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_physics, CAST(@kp_97642cdb76 AS CHAR), 'SINGLE_CHOICE', '【2025高考课标卷物理·第5题】<br>5. 如图，正方形abcd内有方向垂直于纸面的匀强磁场，电子在纸面内从顶点a以速度v0射入磁场，速度方向垂直于ab。磁感应强度的大小不同时，电子可分别从ab边的中点、b点和c点射出，在磁场中运动的时间分别为t1、t2和t3，则（）<div class="question-images"><img src="/images/questions/2025/physics/img_002.png" alt="题目配图"></div>', '["t1&lt;t2=t3", "t1&lt;t2&lt;t3", "t1=t2&gt;t3", "t1&gt;t2&gt;t3"]', 'A', '参考答案：A', 3, '2025高考课标卷物理', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 6, 5);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_physics, CAST(@kp_7e26cc7f7a AS CHAR), 'MULTI_CHOICE', '【2025高考课标卷物理·第6题】<br>6. 如图，一定量的理想气体先后处于 （公式见原题） 图上 （公式见原题） 三个状态，三个状态下气体的压强分别为 （公式见原题） ，则（）<div class="question-images"><img src="/images/questions/2025/physics/img_003.png" alt="题目配图"></div>', '["（公式见原题）", "（公式见原题）", "（公式见原题）", "（公式见原题）"]', 'AD', '参考答案：AD', 4, '2025高考课标卷物理', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 6, 6);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_physics, CAST(@kp_8ef7997009 AS CHAR), 'MULTI_CHOICE', '【2025高考课标卷物理·第7题】<br>7. 一组身高相近的学生沿一直线等间隔排成一排，从左边第一位同学开始，依次周期性地“下蹲、起立”，整个队列呈现类似简谐波的波浪效果，如图所示。假定某次游戏中，形成的波形的波长为4m，左边第一位同学蹲至最低点时，队列中另一同学恰好站直，则这两位同学间的距离可能是（）<div class="question-images"><img src="/images/questions/2025/physics/img_004.png" alt="题目配图"></div>', '["1m", "2m", "5m", "6m"]', 'BD', '参考答案：BD', 4, '2025高考课标卷物理', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 6, 7);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_physics, CAST(@kp_8ef7997009 AS CHAR), 'MULTI_CHOICE', '【2025高考课标卷物理·第8题】<br>8. 如图，过P点的虚线上方存在方向垂直于纸面的匀强磁场。一金属圆环在纸面内以P点为轴沿顺时针方向匀速转动，O为圆环的圆心，OP为圆环的半径。则（）<div class="question-images"><img src="/images/questions/2025/physics/img_005.png" alt="题目配图"></div>', '["圆环中感应电流始终绕O逆时针流动", "OP与虚线平行时圆环中感应电流最大", "圆环中感应电流变化的周期与环转动周期相同", "圆环在磁场内且OP与虚线垂直时环中感应电流最大"]', 'BC', '参考答案：BC', 4, '2025高考课标卷物理', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 6, 8);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_physics, CAST(@kp_da1baf7adf AS CHAR), 'ESSAY', '【2025高考课标卷物理·第9题】<br>9. 某探究小组利用橡皮筋完成下面实验。<br>（1）将粘贴有坐标纸 木板竖直放置。橡皮筋的一端用图钉固定在木板上，另一端悬挂钩码。钩码质量分别为200g、250g、⋯、500g，平衡时橡皮筋底端在坐标纸上对应的位置如图（a）中圆点所示（钩码的质量在图中用数字标出）。悬挂的钩码质量分别为200g和300g时，橡皮筋底端位置间的距离为___________cm。<br>（2）根据图（a）中各点的位置可知，在所测范围内橡皮筋长度的增加量与所挂钩码的__________（选填“质量”或“质量的增加量”）成正比，由此可求出橡皮筋的劲度系数为___________ （公式见原题） （保留2位有效数字，重力加速度取 （公式见原题） ）。<br>（3）悬挂的钩码质量为 （公式见原题） 时，在橡皮筋底端施以水平向右的力 （公式见原题） ，平衡时橡皮筋方向如图（b）中虚线所示，图（b）中测力计的示数给出了力 （公式见原题） 的大小，则 （公式见原题） ___________ （公式见原题） ， （公式见原题） ___________g（选填“200”“300”或“400”）。<div class="question-images"><img src="/images/questions/2025/physics/img_006.png" alt="题目配图"></div>', NULL, '（1）1.90<br>（2） ①. 质量的增加量 ②. 52<br>（3） ①. 1.00 ②. 300', '参考答案：<br>（1）1.90<br>（2） ①. 质量的增加量 ②. 52<br>（3） ①. 1.00 ②. 300', 3, '2025高考课标卷物理', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 15, 9);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_physics, CAST(@kp_da1baf7adf AS CHAR), 'ESSAY', '【2025高考课标卷物理·第10题】<br>10. 用伏安法可以研究电学元件的伏安特性。阻值不随电流、电压变化的元件称为线性电阻元件，否则称为非线性电阻元件。<br>（1）利用伏安法测量某元件的电阻，电流表和电压表的示数分别记为 （公式见原题） 和 （公式见原题） 。若将电流表内接，则 （公式见原题） ___________元件两端的电压， （公式见原题） ___________元件的电阻；将电流表外接，则 （公式见原题） ___________流过元件的电流， （公式见原题） ___________元件的电阻。（均选填“小于”或“大于”）<br>（2）图（a）是某实验小组用电流表内接法测得的某元件的伏安特性曲线，由图可知，所测元件是__________（选填“线性”或“非线性”）电阻元件。随着电流的增加，元件的电阻__________（选填“增大”“不变”或“减小”）。<br>（3）利用电流表 （公式见原题） （内阻 （公式见原题） ）、电流表 （公式见原题） （内阻未知）以及一个用作保护电阻的定值电阻 （公式见原题） （阻值未知），测量电阻 （公式见原题） 的阻值。将图（b）中的器材符号的连线补充完整，完成实验电路原理图__________。按完整的实验电路测量 （公式见原题） ，某次测量中电流表 （公式见原题） 和 （公式见原题） 的示数分别为 （公式见原题） 和 （公式见原题） ，则 （公式见原题） ___________（用 （公式见原题） 和 （公式见原题） 表示）。<div class="question-images"><img src="/images/questions/2025/physics/img_007.png" alt="题目配图"><img src="/images/questions/2025/physics/img_009.png" alt="题目配图"><img src="/images/questions/2025/physics/img_010.png" alt="题目配图"></div>', NULL, '（1） ①. 大于 ②. 大于 ③. 大于 ④. 小于<br>（2） ①. 非线性 ②. 减小<br>（3） ①. ②. （公式见原题）', '参考答案：<br>（1） ①. 大于 ②. 大于 ③. 大于 ④. 小于<br>（2） ①. 非线性 ②. 减小<br>（3） ①. ②. （公式见原题）', 4, '2025高考课标卷物理', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 15, 10);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_physics, CAST(@kp_c35cb6d924 AS CHAR), 'ESSAY', '【2025高考课标卷物理·第11题】<br>11. 电容器 形状变化会导致其电容变化，这一性质可用于设计键盘，简化原理图如图所示。键盘按键下的装置可视为平行板电容器，电容器的极板面积为 （公式见原题） 、间距为 （公式见原题） ，电容 （公式见原题） （ （公式见原题） 为常量）。按下键盘按键时，极板间的距离变为按压前的 （公式见原题） 倍；撤去按压，按键在弹力作用下复位。电容器充电后：<br>（1）若按压按键不改变电容器所带的电荷量，则按压后极板间的电压变为按压前的多少倍？<br>（2）若按压按键不改变电容器极板间的电压，则按压后极板间的电场强度大小变为按压前的多少倍？<div class="question-images"><img src="/images/questions/2025/physics/img_008.png" alt="题目配图"></div>', NULL, '（1） （公式见原题） 倍<br>（2） （公式见原题） 倍', '参考答案：<br>（1） （公式见原题） 倍<br>（2） （公式见原题） 倍', 4, '2025高考课标卷物理', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 15, 11);
INSERT INTO question (subject_id, knowledge_ids, type, content, options, answer, analysis, difficulty, source, created_by, created_at) VALUES (@subject_physics, CAST(@kp_15ccef12ae AS CHAR), 'ESSAY', '【2025高考课标卷物理·第12题】<br>12. 如图，物块P固定在水平面上，其上表面有半径为R的 （公式见原题） 圆弧轨道。P右端与薄板Q连在一起，圆弧轨道与Q上表面平滑连接。一轻弹簧的右端固定在Q上，另一端自由。质量为m的小球自圆弧顶端A点上方的B点自由下落，落到A点后沿圆弧轨道下滑，小球与弹簧接触后，当速度减小至刚接触时的 （公式见原题） 时弹簧的弹性势能为2mgR，此时断开P和Q的连接，从静止开始向右滑动。g为重力加速度大小，忽略空气阻力，圆弧轨道及Q的上、下表面均光滑，弹簧长度的变化始终在弹性限度内。<br>（1）求小球从落入圆弧轨道至离开圆弧轨道，重力对其做的功；<br>（2）求小球与弹簧刚接触时速度的大小及B、A两点间的距离；<br>（3）欲使P和Q断开后，弹簧的最大弹性势能等于2.2mgR，Q的质量应为多大？<br>（4）欲使P和Q断开后，Q的最终动能最大，Q的质量应为多大？', NULL, '（1） （公式见原题）<br>（2） （公式见原题） ， （公式见原题）<br>（3） （公式见原题）<br>（4） （公式见原题）', '参考答案：<br>（1） （公式见原题）<br>（2） （公式见原题） ， （公式见原题）<br>（3） （公式见原题）<br>（4） （公式见原题）', 4, '2025高考课标卷物理', @admin_id, NOW());
SET @question_id := LAST_INSERT_ID();
INSERT INTO exam_question (exam_id, question_id, score, sort_order) VALUES (@exam_id, @question_id, 15, 12);
DROP TEMPORARY TABLE tmp_physics_import_questions;
DROP TEMPORARY TABLE tmp_physics_import_exams;
COMMIT;
